# Generated by Django 4.2.5 on 2024-10-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('official_email', models.EmailField(max_length=254)),
                ('num_employees', models.IntegerField()),
                ('linkedin_url', models.CharField(max_length=100)),
                ('about_content', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
