# Generated by Django 4.2.5 on 2024-11-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_payment_id_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NONE', 'None'), ('REFUND', 'Refund'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PROCESSING', max_length=15, null=True),
        ),
    ]
